# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: [ "orders" ]

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
          cache: 'true'

      - name: Test
        run: |
          cd ${{ matrix.directory }}
          go test ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: [ "orders" ]

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: 'true'

      - name: Build
        run: |
          cd ${{ matrix.directory }}
          go build -v ./...
